version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: pokedex
    networks:
      - pokenet
  mongo-seed:
      build:
          context: ./mongo-seed
          dockerfile: Dockerfile
          args:
            DATABASE_URI: mongodb://root:example@mongo:27017/pokedex?authSource=admin
      depends_on:
        - mongo
      networks:
        - pokenet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - pokenet

networks:
  pokenet: